name: DcCraftWarps
version: 2.6
main: com.dcman58.warpplugin.Main
api-version: 1.13
description: An Awesome way to get around town
load: STARTUP
author: Drew Chase

commands:
  warp:
    description: Main Warp Command
    usage: /warp
  spawn:
    description: Brings You to world Spawn
    usage: /spawn
  warp set:
    description: Sets a Public Warp
    permission: dccraft.warp.set, dccraft.warp.*
    usage: /warp set <name>
  warp set private:
    description: Sets a Private Warp
    usage: /warp set private <name>
  warp help:
    description: Gets a list of all Warp Commands
    usage: /warp help or /warp ?
