main: com.dcman58.warpplugin.Main
name: WarpPlugin
description: An Awesome way to warp to different locations.
version: 0.25
commands: 
  warp: 
    description: Allows you to warp to different waypoints.
  spawn: 
    description: Sends you to Spawn.